<a href="https://colab.research.google.com/github/sqltrainme/Vman/blob/main/Untitled12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/niteen11/DataAnalyticsAcademy/master/Python/dataset_diabetes/diabetic_data.csv',index_col=0)
df

              patient_nbr             race  ... diabetesMed readmitted
encounter_id                                ...
2278392           8222157        Caucasian  ...          No         NO
149190           55629189        Caucasian  ...         Yes        >30
64410            86047875  AfricanAmerican  ...         Yes         NO
500364           82442376        Caucasian  ...         Yes         NO
16680            42519267        Caucasian  ...         Yes         NO
...                   ...              ...  ...         ...        ...
443847548       100162476  AfricanAmerican  ...         Yes        >30
443847782        74694222  AfricanAmerican  ...         Yes         NO
443854148        41088789        Caucasian  ...         Yes         NO
443857166        31693671        Caucasian  ...         Yes         NO
443867222       175429310        Caucasian  ...          No         NO

[101766 rows x 49 columns]

In [ ]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/niteen11/DataAnalyticsAcademy/master/Python/dataset_diabetes/diabetic_data.csv',index_col=0)
df

df.describe()

        patient_nbr  admission_type_id  ...  number_inpatient  number_diagnoses
count  1.017660e+05      101766.000000  ...     101766.000000     101766.000000
mean   5.433040e+07           2.024006  ...          0.635566          7.422607
std    3.869636e+07           1.445403  ...          1.262863          1.933600
min    1.350000e+02           1.000000  ...          0.000000          1.000000
25%    2.341322e+07           1.000000  ...          0.000000          6.000000
50%    4.550514e+07           1.000000  ...          0.000000          8.000000
75%    8.754595e+07           3.000000  ...          1.000000          9.000000
max    1.895026e+08           8.000000  ...         21.000000         16.000000

[8 rows x 12 columns]

In [14]:


import pandas as pd


df = pd.read_csv('https://raw.githubusercontent.com/niteen11/DataAnalyticsAcademy/master/Python/dataset_diabetes/diabetic_data.csv',index_col=0)
df

df.rename(columns={'patient_nbr' : 'patient_ Id','admission_type_id' : 'Admission', 'discharge_disposition_id': 'Discharge', 'admission_source_id' : 'Admission_Source', 'time_in_hospital': 'Hospital Length'}, inplace= True)
df
df.drop('payer_code', axis=1, inplace= True)
df

df['weight'].fillna( 0, inplace=True)
df

              patient_ Id             race  ... diabetesMed readmitted
encounter_id                                ...
2278392           8222157        Caucasian  ...          No         NO
149190           55629189        Caucasian  ...         Yes        >30
64410            86047875  AfricanAmerican  ...         Yes         NO
500364           82442376        Caucasian  ...         Yes         NO
16680            42519267        Caucasian  ...         Yes         NO
...                   ...              ...  ...         ...        ...
443847548       100162476  AfricanAmerican  ...         Yes        >30
443847782        74694222  AfricanAmerican  ...         Yes         NO
443854148        41088789        Caucasian  ...         Yes         NO
443857166        31693671        Caucasian  ...         Yes         NO
443867222       175429310        Caucasian  ...          No         NO

[101766 rows x 48 columns]